plugins { id 'com.android.application' }

android {
    namespace 'cn.acflip.dash'
    compileSdk 36
    defaultConfig {
        applicationId 'cn.acflip.dash'
        minSdk 26
        targetSdk 34
        versionCode 15
        versionName '0.9.0'
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
